### PR TITLE
[switch] Hacked in gyro aiming.

### PR DESCRIPTION
**Pull request by falquinho**
Hi, fgsfdsfgs.
I've managed to get a crude gyro aiming working.
The sensitivity can be controlled with a couple cvars in the config file.
I don't know if the code quality is up to standart, but please consider
adding in your build in some way.
Thanks.

### CODE REVIEW

**Comment by fgsfdsfgs** [comment]
The code seems okay, however running your fork without nxlink (no `-DDEBUG`) makes it crash in a weird way when loading a map. This is probably not your fault, but rather some old bug that hasn't been disturbed before.
Have you experienced anything like that?

**Comment by falquinho** [comment]
Hi fgsfdsfgs.
No, I haven't experienced that. I was able to play a few levels just fine. I compiled with the included makefile and using the latest libnx and libs, so i guess I had the DEBUG flag defined.
I'll try to replicate this problem when I have some time - I'm not a good programmer but I can try and help. 
Thanks for the reply, seeya later .

**Comment by falquinho** [comment]
Hey, fgsfdsfgs.
So, I was playing earlier and I my game crashed.
I played the last half of the 1st world just fine. Upon entering the 2nd world, it crashed.
I restarted the switch and did a bit of testing:
- after restarting, I could load every world just fine. Including 2nd -- the one that crashed before -- tested by pausing and selecting new game. 
- i thougth maybe something to do with the save file, but no, i loaded it and could load the worlds fine.

So this makes think of some kind memory leak? Something not being closed correctly, take causes a crash only after some playtime? When it crashed for you, were you playing for some time, or just turned on, tried to ented a stage and crash?

**Comment by fgsfdsfgs** [comment]
Yeah, I'm thinking it's memory-related.
I just pressed New Game and it crashed after it finished loading.

**Comment by falquinho** [comment]
Hey.
I Spent this afternoon doing lots of fprintf.
Found out that the game, form me, only crashes on TV mode. Portable is fine. Fell dumb for not testing this before.
I disabled 1080p on TV mode and the game no longer crash -- at least on the single stage i was testing.
Also found the last point of execution, the condition "if (realtime - scr_disabled_time > 60)"
on SCR_UpdateScreen.
So, too much memory usage -- im running as applet btw -- causing the loading to take too long and then the game crash?! Thats my take.
I tried but could not understand how the game loads levels. Cant even find where it happens.
Well, guess i'll do my playthrough in 720p.
See ya

**Comment by fgsfdsfgs** [comment]
There were no problems in your code. The crashes were happening due to an unrelated issue. Thank you, I have merged most of your changes that I was able to merge at this point (cf87ffaa5 and 385235cb), also fixed and added some things.

**Pull request closed without merging**
